### ISSUE TITLE
ORS Tools avoid polygon

### ISSUE THREAD

**Issue by jochacronje** [GIScience/orstools-qgis-plugin#118]
Hi,
I am trying to use ORS Tools to avoid a polygon representing an area I want to route around.

I keep getting the following error message:

AttributeError: 'QgsFeature' object has no attribute 'transform' 
Traceback (most recent call last):
  File "C:/Users/User/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\ORStools\gui\ORStoolsDialog.py", line 273, in run_gui_control
    params = directions.get_parameters()
  File "C:/Users/User/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\ORStools\gui\directions_gui.py", line 107, in get_parameters
    geom.transform(transformer)
AttributeError: 'QgsFeature' object has no attribute 'transform'

I am new to QGIS and might be making a rookie mistake. (Am I creating the polygon layer correctly?)
Any help/advise would be highly appreciated.

Regards,
Jocha.

**Comment by mascoto54** [comment]
Hi.
I have the same problem. 
After write to openrouteservice they say:
_This issue is known since about a month.
Sadly we currently don't have the resources to look into it.
Might be a couple of months until this is solved.
But it is open source after all, so there is always the possibility to set it up and debug locally yourself ;-)_

Regards,
Miguel

**Comment by Nisbet99** [comment]
Any idea if there is a fix for this issue?
Been almost 7 months since they said "might be a couple of months until this is solved"!
