### ISSUE TITLE
Uncaught RuntimeError: wrapped C/C++ object of type ORSdirectionsPointsLayersAlgo has been deleted


### ISSUE THREAD

**Issue by baditaflorin** [GIScience/orstools-qgis-plugin#119]
Steps to reproduce
 1. First 
 2. Second 
 3. Third 

```
Traceback (most recent call last):
  File "/Users/florin/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/ORStools/proc/provider.py", line 69, in loadAlgorithms
    self.addAlgorithm(alg)
RuntimeError: wrapped C/C++ object of type ORSdirectionsPointsLayersAlgo has been deleted

```
ORStools 1.2.3, QGIS 3.4.5-Madeira on Darwin 19.6.0

**Comment by bellanz80** [comment]
I have the same error, since several months.
Both in QGIS 3.12, 3.14 and now 3.16

New profile, no plug in
Windows 10

Steps:
1) new profile
2) install the plug
3) enter the settings menu
4) when you click the OK button, the error appears

![image](https://user-images.githubusercontent.com/38449926/100397651-74ac7000-3010-11eb-904b-ca8ebe63b355.png)
![image](https://user-images.githubusercontent.com/38449926/100397672-93126b80-3010-11eb-8e4d-c7f5af78ee6d.png)
![image](https://user-images.githubusercontent.com/38449926/100397682-99084c80-3010-11eb-8452-58eb795a5240.png)

**Comment by bellanz80** [comment]
Hi. I keep with the same error. Is there something that can be modified?
Thanks a lot!

![image](https://user-images.githubusercontent.com/38449926/106292458-75c96b80-6212-11eb-8872-695097263d59.png)
