### ISSUE TITLE
Directions From Points Layer Travel mode does not reflect in output attribute table

### ISSUE THREAD

**Issue by d3netxer** [GIScience/orstools-qgis-plugin#129]
#### Here's what I did
Running a batch job, Directions From Points with driving-car travel mode, and a shortest travel preference.

---
#### Here's what I got
The processing finished successfully. When I opened the output layer it lists 'fastest' under the PREF column

---
#### Here's what I was expecting
I was expecting 'shortest' under the PREF column

---
#### Here's what I think could be improved
In addition the output was actually longer than the result when the 'fastest' option was selected as the preference, so I believe the result may be wrong too.

**Comment by koebi** [comment]
Hey,
running QGIS 3.10 and ORStools 1.3.0, I was not able to reproduce this.
If you find it's still a problem, feel free to reopen.

In this case, please provide a bit more detail to what you did that caused the error, i.e. a screenshot of parameters and log of the batch job and the attributes table of the output layer, and maybe the input layer you used so that it's easier for us to reproduce.
